'use client'

import { useState } from 'react'
import { Logo } from '@/components/ui/logo'
import { apiRequest } from '@/lib/api-client'

export default function DeleteAccountPage() {
  const [email, setEmail] = useState(''); const [reason, setReason] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); try { const data = await apiRequest<{ message?: string }>('/api/khobra-cleaning/public/deletion-request', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, reason }) }); setMessage(data.message || 'Request submitted') } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not submit request') } finally { setSaving(false) } }
  return <main className="min-h-dvh bg-[#f3fbf8] px-5 py-10 text-slate-950"><div className="mx-auto max-w-lg"><a href="/" className="inline-flex min-h-11 items-center"><Logo size={40}/></a><section className="mt-10 rounded-3xl bg-white p-6 shadow-xl shadow-emerald-950/10 sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Privacy request</p><h1 className="mt-3 text-3xl font-black">Request account deletion</h1><p className="mt-3 text-sm leading-6 text-slate-600">We will remove access and personal profile data. Completed bookings, invoices, payments, and audit records may be retained in anonymized form where required.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-bold">Account email<input className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3" type="email" required value={email} onChange={event => setEmail(event.target.value)} /></label><label className="block text-sm font-bold">Reason (optional)<textarea className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 p-3" value={reason} onChange={event => setReason(event.target.value)} /></label>{message && <p role="status" className="text-sm text-emerald-800">{message}</p>}<button disabled={saving} className="min-h-11 rounded-xl bg-emerald-700 px-5 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Submitting…' : 'Submit request'}</button></form></section></div></main>
}
