'use client'

import { FormEvent, useMemo, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { ArrowLeft, ArrowRight, CalendarCheck, CheckCircle2, Clock3, MapPin, Minus, Plus, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { Logo } from '@/components/ui/logo'
import { PublicService, ServiceVisual, usePublicServices } from './public-site'

const tomorrow = () => { const date = new Date(Date.now() + 24 * 60 * 60 * 1000); return date.toISOString().slice(0, 10) }

export function PublicBooking() {
  const query = useSearchParams()
  const { data, isLoading, isError, refetch } = usePublicServices()
  const [selectedId, setSelectedId] = useState(query.get('service') || '')
  const [step, setStep] = useState(1)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')
  const [result, setResult] = useState<{ bookingNo: string; total: number; service: string } | null>(null)
  const [form, setForm] = useState({ name: '', email: '', phone: '', scheduledDate: tomorrow(), startTime: '09:00', duration: 2, employeeCount: 1, preferredPaymentMethod: 'cash', address: '', city: 'Dubai', area: '', notes: '' })
  const selected = data?.services.find(service => service.id === selectedId)
  const currency = data?.business?.currency || 'AED'
  const estimate = useMemo(() => selected ? selected.baseRate * form.duration * form.employeeCount : 0, [selected, form.duration, form.employeeCount])
  const update = (key: string, value: string | number) => setForm(current => ({ ...current, [key]: value }))

  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (!selected) return
    setSubmitting(true); setError('')
    try {
      const response = await fetch('/api/khobra-cleaning/public/bookings', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, serviceId: selected.id }) })
      const body = await response.json()
      if (!response.ok) throw new Error(body.error || 'Could not place booking')
      setResult(body)
    } catch (err) { setError(err instanceof Error ? err.message : 'Could not place booking') }
    finally { setSubmitting(false) }
  }

  if (result) return <main className="grid min-h-screen place-items-center bg-[#effaf6] p-6"><div className="w-full max-w-xl rounded-[2.5rem] border border-white bg-white/85 p-9 text-center shadow-[0_35px_90px_-35px_rgba(5,150,105,.5)] backdrop-blur sm:p-14"><div className="mx-auto grid h-20 w-20 place-items-center rounded-[1.7rem] bg-emerald-100 text-emerald-600 shadow-inner"><CheckCircle2 className="h-11 w-11"/></div><p className="mt-7 text-xs font-black uppercase tracking-[.24em] text-emerald-600">Request confirmed</p><h1 className="mt-3 text-4xl font-black tracking-tight text-slate-950">We&apos;ve got it.</h1><p className="mt-4 text-slate-500">Your {result.service} request is now with our operations team.</p><div className="my-8 rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs uppercase tracking-widest text-white/50">Booking reference</p><p className="mt-1 text-2xl font-black">{result.bookingNo}</p><p className="mt-2 text-sm text-emerald-300">Total: {currency} {result.total.toLocaleString()}</p></div><a href="/" className="inline-flex items-center gap-2 font-bold text-emerald-700"><ArrowLeft className="h-4 w-4"/> Back to home</a></div></main>

  return <main className="min-h-screen bg-[#effaf6] text-slate-950">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><a href="/"><Logo size={42} textClassName="font-black text-sm" subtextClassName="text-[10px] text-emerald-600"/></a><a href="/" className="flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/> Home</a></header>
    <div className="mx-auto grid max-w-7xl gap-8 px-5 pb-16 pt-4 lg:grid-cols-[1fr_420px] lg:px-8">
      <section className="rounded-[2.5rem] border border-white bg-white/80 p-5 shadow-[0_30px_80px_-40px_rgba(6,78,59,.45)] backdrop-blur sm:p-9">
        <div className="mb-8"><p className="text-xs font-black uppercase tracking-[.22em] text-emerald-600">Book in under a minute</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Let&apos;s make your space shine.</h1><div className="mt-6 flex gap-2">{[1,2,3].map(n => <div key={n} className={`h-1.5 flex-1 rounded-full ${n <= step ? 'bg-emerald-500' : 'bg-slate-100'}`}/>)}</div></div>
        {isLoading ? <div className="h-96 animate-pulse rounded-3xl bg-slate-100"/> : isError ? <div role="alert" className="rounded-3xl border border-amber-200 bg-amber-50 p-8 text-center"><h2 className="text-lg font-black">Booking services could not be loaded</h2><p className="mt-2 text-sm text-slate-600">Check your connection and try again.</p><button type="button" onClick={() => void refetch()} className="mt-5 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Try again</button></div> : !data?.services.length ? <div className="rounded-3xl border border-slate-200 bg-white p-8 text-center text-sm font-semibold text-slate-600">No services are currently available for online booking.</div> : <form onSubmit={submit}>
          {step === 1 && <div><h2 className="mb-4 text-lg font-black">Choose a service</h2><div className="grid gap-3 sm:grid-cols-2">{data?.services.map(service => <ServiceChoice key={service.id} service={service} currency={currency} selected={selectedId === service.id} onClick={() => setSelectedId(service.id)}/>)}</div></div>}
          {step === 2 && <div className="space-y-5"><h2 className="text-lg font-black">When should we arrive?</h2><div className="grid gap-4 sm:grid-cols-2"><Field icon={CalendarCheck} label="Date"><input required type="date" min={tomorrow()} value={form.scheduledDate} onChange={e => update('scheduledDate', e.target.value)} className="field"/></Field><Field icon={Clock3} label="Start time"><input required type="time" min={data?.business?.firstBookingTime} max={data?.business?.lastWorkingTime} value={form.startTime} onChange={e => update('startTime', e.target.value)} className="field"/></Field></div><Counter label="Hours" help="2 hour minimum" value={form.duration} min={2} max={8} onChange={value => update('duration', value)}/><Counter label="Cleaning professionals" help="More hands, faster transformation" value={form.employeeCount} min={1} max={10} onChange={value => update('employeeCount', value)}/></div>}
          {step === 3 && <div className="space-y-5"><h2 className="text-lg font-black">Where are we cleaning?</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name"><input required value={form.name} onChange={e => update('name', e.target.value)} className="field" placeholder="Your name"/></Field><Field label="Phone"><input required type="tel" value={form.phone} onChange={e => update('phone', e.target.value)} className="field" placeholder="+971 50 000 0000"/></Field><Field label="Email"><input required type="email" value={form.email} onChange={e => update('email', e.target.value)} className="field" placeholder="you@example.com"/></Field><Field label="City"><input required value={form.city} onChange={e => update('city', e.target.value)} className="field"/></Field></div><Field icon={MapPin} label="Service address"><input required value={form.address} onChange={e => update('address', e.target.value)} className="field" placeholder="Building, street, villa or apartment"/></Field><Field label="Preferred payment method"><select value={form.preferredPaymentMethod} onChange={e => update('preferredPaymentMethod', e.target.value)} className="field"><option value="cash">Pay Cash</option><option value="bank_transfer">Bank Transfer</option></select></Field><p className="-mt-3 text-xs text-slate-500">Payment is only confirmed after cash receipt or bank verification.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Area (optional)"><input value={form.area} onChange={e => update('area', e.target.value)} className="field" placeholder="Marina, JVC..."/></Field><Field label="Notes (optional)"><input value={form.notes} onChange={e => update('notes', e.target.value)} className="field" placeholder="Access or cleaning notes"/></Field></div>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}</div>}
          <div className="mt-8 flex items-center justify-between border-t border-slate-100 pt-6">{step > 1 ? <button type="button" onClick={() => setStep(step - 1)} className="flex items-center gap-2 rounded-xl px-4 py-3 font-bold text-slate-500"><ArrowLeft className="h-4 w-4"/> Back</button> : <span/>}{step < 3 ? <button type="button" disabled={step === 1 && !selected} onClick={() => setStep(step + 1)} className="flex items-center gap-2 rounded-2xl bg-slate-950 px-6 py-3.5 font-bold text-white disabled:opacity-30">Continue <ArrowRight className="h-4 w-4"/></button> : <button disabled={submitting} className="rounded-2xl bg-emerald-600 px-7 py-3.5 font-black text-white shadow-lg shadow-emerald-600/25 disabled:opacity-60">{submitting ? 'Placing booking…' : 'Confirm booking'}</button>}</div>
        </form>}
      </section>
      <aside className="lg:sticky lg:top-6 lg:h-fit">{selected ? <div className="overflow-hidden rounded-[2.2rem] bg-slate-950 text-white shadow-2xl"><ServiceVisual service={selected} className="h-64"/><div className="p-7"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Your clean</p><h2 className="mt-2 text-2xl font-black">{selected.name}</h2><p className="mt-2 text-sm leading-6 text-white/55">{selected.description}</p><div className="my-6 h-px bg-white/10"/><div className="space-y-3 text-sm"><Summary icon={Clock3} label={`${form.duration} hours`}/><Summary icon={Users} label={`${form.employeeCount} professional${form.employeeCount > 1 ? 's' : ''}`}/><Summary icon={ShieldCheck} label="Quality assured"/></div><div className="mt-7 flex items-end justify-between rounded-2xl bg-white/10 p-4"><span className="text-sm text-white/60">Estimated total</span><span className="text-2xl font-black">{currency} {estimate.toLocaleString()}</span></div></div></div> : <div className="rounded-[2.2rem] border border-dashed border-emerald-300 bg-emerald-50 p-9 text-center"><Sparkles className="mx-auto h-10 w-10 text-emerald-500"/><p className="mt-4 font-black">Choose a service</p><p className="mt-2 text-sm text-slate-500">Your booking summary will appear here.</p></div>}</aside>
    </div>
    <style>{`.field{width:100%;height:3rem;border-radius:.85rem;border:1px solid rgb(226 232 240);background:white;padding:0 .9rem;font-size:.875rem;outline:none}.field:focus{border-color:rgb(16 185 129);box-shadow:0 0 0 3px rgb(16 185 129/.12)}`}</style>
  </main>
}

function ServiceChoice({ service, currency, selected, onClick }: { service: PublicService; currency: string; selected: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`overflow-hidden rounded-2xl border-2 text-left transition ${selected ? 'border-emerald-500 bg-emerald-50 shadow-lg shadow-emerald-600/10' : 'border-slate-100 bg-white hover:border-emerald-200'}`}><ServiceVisual service={service} className="h-32"/><div className="p-4"><div className="flex justify-between gap-2"><span className="font-black">{service.name}</span>{selected && <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600"/>}</div><p className="mt-1 text-xs font-semibold text-slate-500">from {currency} {service.baseRate.toLocaleString()} / hour</p></div></button> }
function Field({ icon: Icon, label, children }: { icon?: typeof MapPin; label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 flex items-center gap-2 text-xs font-bold text-slate-600">{Icon && <Icon className="h-3.5 w-3.5 text-emerald-600"/>}{label}</span>{children}</label> }
function Counter({ label, help, value, min, max, onChange }: { label: string; help: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <div className="flex items-center justify-between rounded-2xl border border-slate-100 bg-slate-50 p-4"><div><p className="font-bold">{label}</p><p className="text-xs text-slate-500">{help}</p></div><div className="flex items-center gap-4"><button type="button" aria-label={`Decrease ${label}`} disabled={value <= min} onClick={() => onChange(value - 1)} className="grid h-9 w-9 place-items-center rounded-xl bg-white shadow-sm disabled:opacity-30"><Minus className="h-4 w-4"/></button><span className="w-5 text-center font-black">{value}</span><button type="button" aria-label={`Increase ${label}`} disabled={value >= max} onClick={() => onChange(value + 1)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-white disabled:opacity-30"><Plus className="h-4 w-4"/></button></div></div> }
function Summary({ icon: Icon, label }: { icon: typeof Clock3; label: string }) { return <div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-400/15 text-emerald-300"><Icon className="h-4 w-4"/></div><span>{label}</span></div> }
